### ISSUE TITLE
Don't change camera preview

### ISSUE THREAD

**Issue by Vla2yslav** [dlazaro66/QRCodeReaderView#135] opened 2017-09-09 15:34 UTC
I'm using this code for change camera preview on button click, but it's not work. Can someone help me?

```
public void changeCamera(View view) {
        if (cam == 0)
            cam = 1;
        else cam = 0;

        if (cam == 0) 
            qrCodeReaderView.setBackCamera();
        else 
            qrCodeReaderView.setFrontCamera();
 }
```

**Comment by dlazaro66** [comment] 2017-10-14 11:41
duplicate of #110

**Closed by dlazaro66** 2017-10-14 11:41 UTC
Labels: duplicate
